// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    App: typeof import('./../components/App.vue')['default']
    AppContainer: typeof import('./../components/shared/AppContainer/AppContainer.vue')['default']
    AppHeader: typeof import('./../components/AppHeader/AppHeader.vue')['default']
    MyCardsIcon: typeof import('./../components/icons/MyCardsIcon.vue')['default']
    MyGoalsIcon: typeof import('./../components/icons/MyGoalsIcon.vue')['default']
    NavigationList: typeof import('./../components/AppHeader/NavigationList/NavigationList.vue')['default']
    SettingsIcon: typeof import('./../components/icons/SettingsIcon.vue')['default']
  }
}

export { }
